### ISSUE TITLE
Proprietary and confidential notice inside basic_test.cpp

### ISSUE THREAD

**Issue by rfzeg** [AndyZe/minimal_integration_test#1]
minimal_integration_test's code is open source under the BSD-3-Clause license. This allows anyone to examine, modify and distribute the sources (among other things). However, the source code repository includes a documentation file that has a "Proprietary and confidential" notice:

https://github.com/AndyZe/minimal_integration_test/blob/515bfda90ebec727256f9552168a1bd328dc98c8/test/basic_test.cpp#L4

I suspect this is a mistake since other files do not carry such a notice.

**Steps to Reproduce**   
Open and read: https://github.com/AndyZe/minimal_integration_test/blob/515bfda90ebec727256f9552168a1bd328dc98c8/test/basic_test.cpp#L4
  
**Expected Behavior**   
This is all open source and publicly usable.

**Actual Behavior**  
There is a "Proprietary and confidential." notice.

**Comment by AndyZe** [comment]
Thanks! It should be fixed now.
