### ISSUE TITLE
How to run the minimal test

### ISSUE THREAD

**Issue by Nate711** [AndyZe/minimal_integration_test#2]
Hi, dumb question, but I'm trying to learn how to run ROS tests and was wondering how to actually run this. I did 

``ros2 test src/minimal_integration_test/test/launch/basic_test.test.py``

but I got an error 

``[ERROR] [launch]: Caught exception in launch (see debug for traceback): Included launch description missing required argument 'test_binary_dir' (description: 'Binary directory of package containing test executables'), given: []``

Thanks!

**Comment by AndyZe** [comment]
It's just:

`colcon build`

`colcon test minimal_integration_test`

If that works for you, can you please open a PR to add that to the README?

**Comment by Nate711** [comment]
Thanks for the fast response! I needed ``colcon test --packages-select minimal_integration_test``

**Comment by Nate711** [comment]
I've now encountered weird behavior where if I test more than once after a colcon build it fails:
1. ``colcon build``
2. ``colcon test --packages-select minimal_integration_test``
(passes)
3.  ``colcon test --packages-select minimal_integration_test``
```
Starting >>> minimal_integration_test
--- stderr: minimal_integration_test                   
Errors while running CTest
Output from these tests are in:[workspace]/build/minimal_integration_test/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
---
Finished <<< minimal_integration_test [0.97s]	[ with test failures ]

Summary: 1 package finished [1.08s]
  1 package had stderr output: minimal_integration_test
  1 package had test failures: minimal_integration_test
```
And then annoyingly, although no fault of this repo, the suggestion to use ``--rerun-failed --output-on-failure`` isn't actually a valid argument according to colcon test: 
```
colcon test --rerun-failed --output-on-failure --packages-select minimal_integration_test
```
```
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
              {build,extension-points,extensions,graph,info,list,metadata,test,test-result,version-check} ...
colcon: error: unrecognized arguments: --rerun-failed --output-on-failure
```
Maybe the doc string is outdated.

**Comment by AndyZe** [comment]
That's strange. `colcon test` has been good for me but I'm not sure I ever tried running it twice in a row on this package. What version of ROS2 are you on?

**Comment by Nate711** [comment]
I'm on humble
